#!/usr/bin/env python3
"""
reset_to_base.py — reset a Rubicon Seven CAMPAIGN folder to the blank Day-1 scaffold.

Run this before shipping a campaign template, or to start a fresh campaign in place. It REMOVES
every artifact that /vaarn-start generates and REWRITES the blank Day-1 skeleton, while KEEPING
the per-machine config and the skill itself.

  WIPE (removed)      : CLAUDE.md, .claude/settings.json, .claude/memories.json (personal
                        memory blob — never ship it), everything in .claude/output-styles/,
                        every character sheet, everything in prep/ maps/ vehicles/, and the
                        contents of chroma-db/.
  RESET (rewritten)   : CURRENT_STATUS.md, ANTAGONIST_CULTIVATION.md, MASTER_CONTINUITY_CURRENT.md,
                        lorebook.json, NPC_ROSTER.md, characters/_meta.json, .gitignore (the
                        leak guard)  -> blank Day-1.
  KEEP (never touched): README*.md, .mcp.json (machine/engine config), .claude/skills/**.

The strip-list and the generate-list are the same list: anything onboarding creates, this undoes.

  ⚠ --dir IS REQUIRED. This tool lives in the ENGINE repo, but it operates on a CAMPAIGN
  folder — never on the engine itself. You must name the target campaign explicitly; there is
  no default, so it can never accidentally wipe the engine's own CLAUDE.md/settings.

Dry-run by default — prints what it WOULD do. Pass --apply to actually make changes.

    python3 scripts/reset_to_base.py --dir /path/to/campaign            # preview (safe)
    python3 scripts/reset_to_base.py --dir /path/to/campaign --apply    # do it
"""
from __future__ import annotations

import argparse
import shutil
import sys
from datetime import date
from pathlib import Path

# Single source of truth for the blank Day-1 file contents + the engine-repo guard.
# scaffold_campaign.py owns them; this reset tool only adds the WIPE policy on top.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from scaffold_campaign import (  # noqa: E402
    CURRENT_STATUS, MASTER_CONTINUITY, ANTAGONIST, META_JSON,
    LOREBOOK, NPC_ROSTER, GITIGNORE, ENGINE_SIGNATURES,
)

# Files removed outright (generated by onboarding; base has none of these).
REMOVE_FILES = [
    "CLAUDE.md",
    ".claude/settings.json",
    # Claude Code's per-folder personal-memory store (undocumented; can hold personal context
    # + the user's account id). The base scaffold NEVER carries one — Claude makes its own clean
    # copy under the current user's account if/when needed. Wiping it here means a reset-to-base
    # (e.g. before shipping a template) can never leave a previous owner's personal blob behind.
    ".claude/memories.json",
]

# Directory contents emptied (files removed; the directory itself is kept).
CLEAR_DIRS = [
    ".claude/output-styles",
    "prep",
    "maps",
    "vehicles",
    "chroma-db",
]

# Files rewritten to blank Day-1 content (contents imported from scaffold_campaign).
RESET_FILES = {
    "CURRENT_STATUS.md": CURRENT_STATUS,
    "MASTER_CONTINUITY_CURRENT.md": MASTER_CONTINUITY,
    "ANTAGONIST_CULTIVATION.md": ANTAGONIST,
    "lorebook.json": LOREBOOK,
    "NPC_ROSTER.md": NPC_ROSTER,
    ".gitignore": GITIGNORE,
}

# A campaign folder MUST look like one before we wipe it. Two-sided guard so this can
# never nuke the engine repo (which also has a .mcp.json, so a positive marker alone is
# not enough — we ALSO refuse anything carrying engine source files).
CAMPAIGN_MARKERS = ["CURRENT_STATUS.md", "ANTAGONIST_CULTIVATION.md"]
# ENGINE_SIGNATURES imported from scaffold_campaign (shared engine-repo guard).


def main() -> int:
    parser = argparse.ArgumentParser(description="Reset a CAMPAIGN folder to the blank Day-1 scaffold.")
    parser.add_argument("--dir", required=True,
                        help="REQUIRED. The campaign folder to reset (never the engine repo).")
    parser.add_argument("--apply", action="store_true",
                        help="Actually make changes. Without this, runs as a dry-run preview.")
    args = parser.parse_args()

    root = Path(args.dir).resolve()
    apply = args.apply
    tag = "APPLY" if apply else "DRY-RUN"

    if not root.exists():
        print(f"[{tag}] ERROR: campaign folder not found: {root}")
        return 1

    # Safety 1: refuse anything carrying engine source — this is the engine, not a campaign.
    engine_hits = [s for s in ENGINE_SIGNATURES if (root / s).exists()]
    if engine_hits:
        print(f"[{tag}] ERROR: {root} looks like the ENGINE repo (found {engine_hits}), not a campaign.")
        print(f"[{tag}]        Refusing — this tool resets campaign folders only.")
        return 1

    # Safety 2: require a positive campaign marker before wiping.
    if not any((root / m).exists() for m in CAMPAIGN_MARKERS):
        print(f"[{tag}] ERROR: {root} does not look like a Rubicon Seven campaign folder")
        print(f"[{tag}]        (none of {CAMPAIGN_MARKERS} present). Refusing to touch it.")
        return 1

    print(f"[{tag}] Resetting campaign folder: {root}")
    print(f"[{tag}] KEEP: README*.md, .mcp.json, .claude/skills/**\n")

    def remove(p: Path) -> None:
        if not p.exists():
            return
        print(f"[{tag}] remove  {p.relative_to(root)}")
        if apply:
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()

    def write(rel: str, content: str) -> None:
        p = root / rel
        print(f"[{tag}] reset   {rel}")
        if apply:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")

    # 1. Remove generated files.
    for rel in REMOVE_FILES:
        remove(root / rel)

    # 2. Empty generated directories (keep the directory shells).
    for rel in CLEAR_DIRS:
        d = root / rel
        if d.exists():
            for child in sorted(d.iterdir()):
                remove(child)
        elif apply:
            d.mkdir(parents=True, exist_ok=True)

    # 3. characters/: wipe every sheet, then rewrite a blank _meta.json.
    chars = root / "characters"
    if chars.exists():
        for child in sorted(chars.iterdir()):
            remove(child)
    write("characters/_meta.json", META_JSON.format(today=date.today().isoformat()))

    # 4. Rewrite the blank world files.
    for rel, content in RESET_FILES.items():
        write(rel, content)

    print()
    if apply:
        print(f"[{tag}] Done. Folder reset to the blank Day-1 scaffold.")
    else:
        print(f"[{tag}] Preview only — nothing changed. Re-run with --apply to commit.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
